package com.vinh.identify_identity_card.ui.manual

enum class ManualField {
    IDENTITYCARD_ID,
    IDENTITYCARD_NAME,
    IDENTITYCARD_DOB,
    IDENTITYCARD_GENDER,
    IDENTITYCARD_NATIONALITY,
    IDENTITYCARD_ORIGIN,
    IDENTITYCARD_RESIDENCE,
    IDENTITYCARD_ISSUE_DATE,
    IDENTITYCARD_EXPIRY_DATE,
    IDENTITYCARD_ISSUE_PLACE,

    // PASSPORTPORT
    PASSPORT_ID,
    PASSPORT_NAME,
    PASSPORT_DOB,
    PASSPORT_GENDER,
    PASSPORT_NATIONALITY,
    PASSPORT_NO,
    PASSPORT_ISSUE_DATE,
    PASSPORT_EXPIRY_DATE,
    PASSPORT_AUTHORITY
}